- name: Run Postgresql container
  hosts: vm
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: install pip dependencies
      pip:
        name: docker

    - name: Create Postgres Container
      docker_container:
          name: hitch_postgres
          image: postgres:12
          state: started
          recreate: yes
          ports:
            - "5432:5432"
          volumes:
            - /home/hitch_postgres_data:/var/lib/postgresql/data
          env:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "pass1234"